### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by miguelalbox** [miguelalbox/P6_SnowTricks#10]
- [ ] lien vers créer une compte #6 
- [ ] Se déconnecter (si connecté) #11 
- [ ] lien vers la page de connexion #4 
- [ ] lien vers page des Tricks #8
- [ ] lien vers la page d'accueil #9
