### ISSUE TITLE
Afficher / Créer / Modifier page figure

### ISSUE THREAD

**Issue by miguelalbox** [miguelalbox/P6_SnowTricks#7]
**commun**
- [ ] Afficher le groupe #12 
- [ ] Afficher les medias #5 
- [ ] Afficher une image d'accueil
- [ ] Afficher la description et autres informations #14 
- [ ] Afficher le groupe #12 

**spécifique à la création**

**spécifique à la modification**

**spécifique à l'affichage**
- [ ] Système de pagination des commentaires
- [ ] Afficher les commentaires #13 
- [ ] Afficher si la figure nous appartient le bouton modifier
- [ ] Afficher si la figure nous appartient le bouton suppression
- [ ] Afficher un formulaire pour ajouter un commentaire #13
